main:
  controller:
    \Policeamunice\MVC\Controllers\MainController
  actions:
    - index

contacts:
  controller:
    \Policeamunice\MVC\Controllers\ContactsController
  actions:
    - index
    - feedback

portfolio:
  controller:
    \Policeamunice\MVC\Controllers\PortfolioController
  actions:
    - index

service:
  controller:
    \Policeamunice\MVC\Controllers\ServiceController
  actions:
    - index

404:
  controller:
    \Policeamunice\MVC\Controllers\NotFoundController
  actions:
    - index
