# WEB
FROM nginx:1.17.8-alpine as web

COPY ./public/ /app/public/

COPY ./configs/docker/default.conf /etc/nginx/conf.d/default.conf


# PHP
FROM php:8.1.8-fpm-alpine3.16 as php

COPY ./configs/docker/php-fpm.conf /usr/local/etc/php-fpm.d/www.conf

COPY . /app

VOLUME ["/app"]
